// Connections between company "planets" — the lines drawn on the map.
//
// - `from` / `to` are company names (must match the sheet's company names,
//   same identifiers used as keys in COMPANY_POSITIONS).
// - `style: "solid"`  → wholly owned / closed acquisition.
// - `style: "dotted"` → not wholly owned, or an acquisition still in process.
// - `description` shows in a tooltip when the line is hovered.
//
// This file is the source-of-truth for connections. The in-app design mode
// (`?edit=1` URL flag) lets you draw connections by clicking two planets and
// exports a fresh version of this array to paste back here.
export type ConnectionStyle = "solid" | "dotted";

export type Connection = {
  from: string;
  to: string;
  style: ConnectionStyle;
  description: string;
};


// Generated by the in-app design mode. Replace COMPANY_CONNECTIONS in src/connections.ts with this.
// Generated by the in-app design mode. Replace COMPANY_CONNECTIONS in src/connections.ts with this.
export const COMPANY_CONNECTIONS: Connection[] = [
  { from: "Paramount Skydance", to: "Oracle", style: "solid", description: "Oracle and Paramount are now linked by one of media’s most powerful family-business alliances: Larry Ellison and his son, David Ellison." },
  { from: "ByteDance", to: "Oracle", style: "solid", description: "" },
  { from: "Paramount Skydance", to: "WBD", style: "solid", description: "" },
  { from: "Epic", to: "Tencent", style: "dotted", description: "" },
  { from: "Tencent", to: "Riot", style: "solid", description: "" },
  { from: "Charter", to: "Comcast", style: "dotted", description: "" },
  { from: "TEGNA", to: "Nexstar", style: "dotted", description: "" },
  { from: "Hearst", to: "Disney", style: "dotted", description: "" },
  { from: "ProSieben", to: "MFE", style: "dotted", description: "" },
];


