// Per-company position overrides. Sector centers (sectors.ts) provide the
// default gravity well for every planet in a sector; entries here override
// that on a per-planet basis.
//
// - `x`, `y` are slide-coordinate space (same as SECTOR_CENTERS).
// - `pin: true`  → planet is pinned to (x, y). d3-force won't move it; other
//                  planets collide against it.
// - `pin` absent → (x, y) becomes the planet's force attractor. Physics still
//                  resolves collisions; the planet drifts if a neighbor pushes
//                  it. Use this for "I want X near Y but I don't care which
//                  side of Y."
//
// This file is the source-of-truth for layout. The in-app design mode
// (`?edit=1` URL flag) lets you drag planets and exports a fresh version of
// this file to paste back here.
export type PlanetPosition = {
  x: number;
  y: number;
  pin?: boolean;
};

// Generated by the in-app design mode. Replace COMPANY_POSITIONS in src/layout.ts with this.
// Generated by the in-app design mode. Replace COMPANY_POSITIONS in src/layout.ts with this.
// Generated by the in-app design mode. Replace COMPANY_POSITIONS in src/layout.ts with this.
// Generated by the in-app design mode. Replace COMPANY_POSITIONS in src/layout.ts with this.
// Generated by the in-app design mode. Replace COMPANY_POSITIONS in src/layout.ts with this.
// Generated by the in-app design mode. Replace COMPANY_POSITIONS in src/layout.ts with this.
// Generated by the in-app design mode. Replace COMPANY_POSITIONS in src/layout.ts with this.
// Generated by the in-app design mode. Replace COMPANY_POSITIONS in src/layout.ts with this.
export const COMPANY_POSITIONS: Record<string, PlanetPosition> = {
  "Alibaba": { x: 2074, y: -815, pin: true },
  "Alphabet": { x: -1143, y: -545, pin: true },
  "Amazon": { x: 830, y: -699, pin: true },
  "Apple": { x: -1577, y: 998, pin: true },
  "ByteDance": { x: 260, y: 1299, pin: true },
  "Charter": { x: -371, y: -472 },
  "Comcast": { x: -199, y: -389 },
  "COX": { x: -492, y: -58, pin: true },
  "Disney": { x: -70, y: -124, pin: true },
  "Hearst": { x: -315, y: 3, pin: true },
  "META": { x: -555, y: 1533, pin: true },
  "MFE": { x: 418, y: 144, pin: true },
  "Microsoft": { x: 1593, y: 1429, pin: true },
  "Netflix": { x: -123, y: 454, pin: true },
  "Nexstar": { x: -526, y: -979, pin: true },
  "Nvidia": { x: 1982, y: 221, pin: true },
  "Oracle": { x: 694, y: 1700, pin: true },
  "Paramount Skydance": { x: 626, y: 1032, pin: true },
  "ProSieben": { x: 551, y: 242, pin: true },
  "Reliance": { x: -1175, y: 1692, pin: true },
  "Samsung": { x: -105, y: -867, pin: true },
  "TEGNA": { x: -619, y: -1117, pin: true },
  "Tencent": { x: 2544, y: -708, pin: true },
  "WALMART": { x: 1608, y: -1207, pin: true },
  "WBD": { x: 639, y: 743, pin: true },
};









