// Per-view-type mobile layouts — the mobile counterpart to layout.ts, one
// independent layout per mobile view type (full / vertical / horizontal). Each
// has its own physics settings, hand-placed planet positions, and sector
// gravity wells, all separate from desktop AND from each other. Authored in the
// browser via `?edit=mobile` (view-type selector + drag + sliders), then copied
// back here. Coordinates are in each type's own canvas slide-space.
//
// Local fallback, same pattern as layout.ts: a future Sanity migration swaps
// these for per-view-type fields on each company.
export type MobilePosition = { x: number; y: number };
export type MobileViewType = "full" | "vertical" | "horizontal" | "square";

export type MobileSettings = {
  scale: number; // planet-size multiplier (1 = auto)
  collidePadding: number; // min gap between planets (no overlap)
  sizeSpacing: number; // extra gap scaled by planet radius
  repulsion: number; // long-range push that fills empty space
  sectorPull: number; // gravity toward each sector's center (lower = fills more)
  nameThreshold: number; // min on-screen planet diameter (px) to show a name
};

export type MobileLayout = {
  settings: MobileSettings;
  positions: Record<string, MobilePosition>; // hand-placed planets (pinned)
  sectorCenters: Record<string, MobilePosition>; // per-sector gravity wells
};

// Generated by ?edit=mobile. Paste over MOBILE_LAYOUTS here.
export const MOBILE_LAYOUTS: Record<MobileViewType, MobileLayout> = {
  full: {
    settings: { scale: 1.000, collidePadding: 12, sizeSpacing: 0.050, repulsion: 16, sectorPull: 0.050, nameThreshold: 10 },
    sectorCenters: {
      "Advertising": { x: -1289, y: 466 },
      "Audio": { x: -787, y: 929 },
      "Content Platform": { x: 1054, y: -349 },
      "Exhibition": { x: 198, y: 476 },
      "Gaming": { x: 1436, y: -727 },
      "Hardware/Physical": { x: 1070, y: 164 },
      "HoldingCo": { x: -453, y: 54 },
      "Large Cap": { x: -1145, y: -1336 },
      "Local TV": { x: -535, y: -835 },
      "MVPD/BB": { x: 233, y: -573 },
      "PSM": { x: -1683, y: -98 },
      "Publishing": { x: -1070, y: 1468 },
      "Sports Leagues": { x: 697, y: 540 },
      "Studio": { x: 334, y: -94 },
      "Telecom": { x: -1589, y: -1141 },
    },
    positions: {
      "Alibaba": { x: 2281, y: -1167 },
      "Alphabet": { x: -1139, y: -422 },
      "Amazon": { x: 658, y: -1095 },
      "Apple": { x: -1969, y: 1199 },
      "ByteDance": { x: -56, y: 1070 },
      "META": { x: -426, y: 2071 },
      "Microsoft": { x: 1261, y: 1341 },
      "Nexstar": { x: -643, y: -962 },
      "Open AI": { x: 1995, y: 2060 },
      "Oracle": { x: 468, y: 1805 },
      "Paramount Skydance": { x: 472, y: 1222 },
      "Reliance": { x: -1172, y: 2012 },
      "Samsung": { x: -292, y: -1396 },
      "Space X": { x: 2458, y: 1423 },
      "TEGNA": { x: -745, y: -1108 },
      "Tik Tok US": { x: 219, y: 1429 },
      "WALMART": { x: 1651, y: -1371 },
      "WBD": { x: 465, y: 952 },
    },
  },
  vertical: {
    settings: { scale: 1.000, collidePadding: 12, sizeSpacing: 0.050, repulsion: 26, sectorPull: 0.050, nameThreshold: 5 },
    sectorCenters: {
      "Advertising": { x: 414, y: -302 },
      "Audio": { x: -384, y: 414 },
      "Content Platform": { x: 195, y: -561 },
      "Exhibition": { x: 125, y: 806 },
      "Gaming": { x: 525, y: -912 },
      "Hardware/Physical": { x: 297, y: 3 },
      "HoldingCo": { x: -321, y: -416 },
      "Large Cap": { x: 143, y: 1593 },
      "Local TV": { x: -350, y: -766 },
      "MVPD/BB": { x: 69, y: -934 },
      "PSM": { x: -775, y: -225 },
      "Publishing": { x: -278, y: 75 },
      "Social/Creator": { x: -511, y: 763 },
      "Sports Leagues": { x: 310, y: 435 },
      "Studio": { x: 631, y: -529 },
      "Telecom": { x: -546, y: -1045 },
    },
    positions: {
      "Access": { x: -452, y: -170 },
      "Alibaba": { x: 706, y: -1171 },
      "Alphabet": { x: -828, y: -655 },
      "Amazon": { x: 863, y: -583 },
      "Antrhopic": { x: 506, y: 799 },
      "Apple": { x: -916, y: 291 },
      "ByteDance": { x: -117, y: 307 },
      "Charter": { x: -54, y: -759 },
      "Comcast": { x: -23, y: -537 },
      "COX": { x: 47, y: -805 },
      "DAZN": { x: -334, y: -173 },
      "Deezer": { x: -557, y: -169 },
      "Disney": { x: 139, y: -386 },
      "Epic": { x: 282, y: -612 },
      "Marvel": { x: 136, y: -241 },
      "META": { x: -848, y: 910 },
      "MFE": { x: 431, y: -497 },
      "Microsoft": { x: -118, y: 1177 },
      "Netflix": { x: -80, y: -222 },
      "Nexstar": { x: -271, y: -688 },
      "Nvidia": { x: 808, y: 173 },
      "Open AI": { x: 562, y: 1150 },
      "Oracle": { x: 136, y: 658 },
      "Paramount Skydance": { x: 129, y: 349 },
      "ProSieben": { x: 490, y: -432 },
      "Reliance": { x: -294, y: 695 },
      "Riot": { x: 206, y: -695 },
      "Samsung": { x: -249, y: -1168 },
      "Space X": { x: 914, y: 831 },
      "TEGNA": { x: -263, y: -784 },
      "Tencent": { x: 375, y: -777 },
      "Tik Tok US": { x: 4, y: 474 },
      "WALMART": { x: 281, y: -1169 },
      "WBD": { x: 120, y: 130 },
      "WMG": { x: -451, y: -31 },
      "Xumo": { x: -147, y: -668 },
    },
  },
  // Landscape (rotated-phone) view. Inherits the full view's placement + wells at
  // runtime (own entries override per-planet); settings are independent. On a
  // portrait phone it shows a "rotate your phone" prompt instead of the map.
  horizontal: {
    settings: { scale: 1.000, collidePadding: 12, sizeSpacing: 0.050, repulsion: 16, sectorPull: 0.050, nameThreshold: 10 },
    sectorCenters: {},
    positions: {},
  },
  // 1:1 view. Also inherits the full view's placement + wells at runtime; its own
  // settings start equal to full's and can be tuned independently.
  square: {
    settings: { scale: 1.000, collidePadding: 12, sizeSpacing: 0.050, repulsion: 16, sectorPull: 0.050, nameThreshold: 10 },
    sectorCenters: {},
    positions: {},
  },
};
