// Per-view-type mobile layouts — the mobile counterpart to layout.ts, one
// independent layout per mobile view type (full / vertical / horizontal /
// square). Each has its own physics settings, hand-placed planet positions, and
// sector gravity wells, all separate from desktop AND from each other. Authored
// in the browser via `?edit=mobile` (view-type selector + drag + sliders), then
// copied back here. Coordinates are in each type's own canvas slide-space.
//
// Local fallback, same pattern as layout.ts: a future Sanity migration swaps
// these for per-view-type fields on each company.
export type MobilePosition = { x: number; y: number };
export type MobileViewType = "full" | "vertical" | "horizontal" | "square";

export type MobileSettings = {
  scale: number; // planet-size multiplier (1 = auto)
  collidePadding: number; // min gap between planets (no overlap)
  sizeSpacing: number; // extra gap scaled by planet radius
  repulsion: number; // long-range push that fills empty space
  sectorPull: number; // gravity toward each sector's center (lower = fills more)
  nameThreshold: number; // min on-screen planet diameter (px) to show a name
};

export type MobileLayout = {
  settings: MobileSettings;
  positions: Record<string, MobilePosition>; // hand-placed planets (pinned)
  sectorCenters: Record<string, MobilePosition>; // per-sector gravity wells
};

// Generated by ?edit=mobile. Paste over MOBILE_LAYOUTS here.
export const MOBILE_LAYOUTS: Record<MobileViewType, MobileLayout> = {
  full: {
    settings: { scale: 1.000, collidePadding: 12, sizeSpacing: 0.050, repulsion: 16, sectorPull: 0.050, nameThreshold: 10 },
    sectorCenters: {
      "Advertising": { x: -1185, y: 487 },
      "Audio": { x: -897, y: 1025 },
      "Content Platform": { x: 999, y: -328 },
      "Exhibition": { x: 281, y: 530 },
      "Gaming": { x: 1498, y: -754 },
      "Hardware/Physical": { x: 953, y: 274 },
      "HoldingCo": { x: -453, y: 54 },
      "Large Cap": { x: -1145, y: -1336 },
      "Local TV": { x: -398, y: -876 },
      "MVPD/BB": { x: 233, y: -573 },
      "PSM": { x: -1834, y: 66 },
      "Publishing": { x: -1070, y: 1523 },
      "Social/Creator": { x: -133, y: 1388 },
      "Sports Leagues": { x: 978, y: 883 },
      "Studio": { x: 341, y: -217 },
      "Telecom": { x: -1883, y: -803 },
    },
    positions: {
      "Access": { x: -365, y: 322 },
      "Alibaba": { x: 2281, y: -1167 },
      "Alphabet": { x: -1063, y: -380 },
      "Amazon": { x: 665, y: -1143 },
      "Antrhopic": { x: 2749, y: 789 },
      "Apple": { x: -1969, y: 1199 },
      "ByteDance": { x: -56, y: 1070 },
      "Charter": { x: -12, y: -460 },
      "Comcast": { x: -4, y: -234 },
      "COX": { x: 208, y: -458 },
      "DAZN": { x: -530, y: 327 },
      "Deezer": { x: -151, y: 325 },
      "Disney": { x: 341, y: 140 },
      "Hearst": { x: -233, y: 3 },
      "Marvel": { x: 348, y: 345 },
      "META": { x: -337, y: 2105 },
      "MFE": { x: 727, y: 151 },
      "Microsoft": { x: 1371, y: 1863 },
      "Netflix": { x: -439, y: 778 },
      "Nexstar": { x: -643, y: -962 },
      "Open AI": { x: 2290, y: 2266 },
      "Oracle": { x: 468, y: 1805 },
      "Paramount Skydance": { x: 472, y: 1222 },
      "ProSieben": { x: 858, y: 150 },
      "Reliance": { x: -1172, y: 2012 },
      "Samsung": { x: -306, y: -1423 },
      "Space X": { x: 2430, y: 1519 },
      "TEGNA": { x: -745, y: -1108 },
      "Tik Tok US": { x: 219, y: 1429 },
      "WALMART": { x: 1651, y: -1371 },
      "WBD": { x: 465, y: 952 },
      "WMG": { x: -337, y: 488 },
      "Xumo": { x: -220, y: -379 },
    },
  },
  vertical: {
    settings: { scale: 1.000, collidePadding: 12, sizeSpacing: 0.050, repulsion: 26, sectorPull: 0.050, nameThreshold: 5 },
    sectorCenters: {
      "Advertising": { x: 414, y: -302 },
      "Audio": { x: -384, y: 414 },
      "Content Platform": { x: 195, y: -561 },
      "Exhibition": { x: 125, y: 806 },
      "Gaming": { x: 525, y: -912 },
      "Hardware/Physical": { x: 297, y: 3 },
      "HoldingCo": { x: -321, y: -416 },
      "Large Cap": { x: 143, y: 1593 },
      "Local TV": { x: -350, y: -766 },
      "MVPD/BB": { x: 69, y: -934 },
      "PSM": { x: -775, y: -225 },
      "Publishing": { x: -278, y: 75 },
      "Social/Creator": { x: -511, y: 763 },
      "Sports Leagues": { x: 310, y: 435 },
      "Studio": { x: 631, y: -529 },
      "Telecom": { x: -546, y: -1045 },
    },
    positions: {
      "Access": { x: -452, y: -170 },
      "Alibaba": { x: 706, y: -1171 },
      "Alphabet": { x: -851, y: -652 },
      "Amazon": { x: 863, y: -583 },
      "Antrhopic": { x: 506, y: 799 },
      "Apple": { x: -919, y: 248 },
      "ByteDance": { x: -117, y: 307 },
      "Charter": { x: -54, y: -759 },
      "Comcast": { x: -23, y: -537 },
      "COX": { x: 47, y: -805 },
      "DAZN": { x: -334, y: -173 },
      "Deezer": { x: -557, y: -169 },
      "Disney": { x: 139, y: -386 },
      "Epic": { x: 282, y: -612 },
      "Marvel": { x: 136, y: -241 },
      "META": { x: -848, y: 910 },
      "MFE": { x: 431, y: -497 },
      "Microsoft": { x: -118, y: 1177 },
      "Netflix": { x: -80, y: -222 },
      "Nexstar": { x: -271, y: -688 },
      "Nvidia": { x: 808, y: 173 },
      "Open AI": { x: 562, y: 1150 },
      "Oracle": { x: 136, y: 658 },
      "Paramount Skydance": { x: 129, y: 349 },
      "ProSieben": { x: 490, y: -432 },
      "Reliance": { x: -294, y: 695 },
      "Riot": { x: 206, y: -695 },
      "Samsung": { x: -249, y: -1168 },
      "Space X": { x: 914, y: 831 },
      "TEGNA": { x: -263, y: -784 },
      "Tencent": { x: 375, y: -777 },
      "Tik Tok US": { x: 4, y: 474 },
      "WALMART": { x: 281, y: -1169 },
      "WBD": { x: 120, y: 130 },
      "WMG": { x: -451, y: -31 },
      "Xumo": { x: -147, y: -668 },
    },
  },
  // Landscape (rotated-phone) view. Empty entries inherit the full view's
  // placement + wells at runtime; these override it. Portrait → rotate prompt.
  horizontal: {
    settings: { scale: 1.000, collidePadding: 12, sizeSpacing: 0.050, repulsion: 16, sectorPull: 0.050, nameThreshold: 10 },
    sectorCenters: {
      "Audio": { x: -766, y: 894 },
      "Content Platform": { x: 962, y: -335 },
      "Exhibition": { x: 64, y: 462 },
      "Gaming": { x: 1401, y: -699 },
      "Hardware/Physical": { x: 851, y: 107 },
      "Studio": { x: 158, y: -172 },
    },
    positions: {
      "Alibaba": { x: 2281, y: -1167 },
      "Antrhopic": { x: 2799, y: 734 },
      "Epic": { x: 2289, y: -707 },
      "META": { x: -426, y: 1916 },
      "Microsoft": { x: 1247, y: 1292 },
      "Nvidia": { x: 1891, y: 129 },
      "Open AI": { x: 1988, y: 1905 },
      "Reliance": { x: -1207, y: 1920 },
      "Riot": { x: 2409, y: -531 },
      "Samsung": { x: -348, y: -1269 },
      "Space X": { x: 2543, y: 1438 },
      "Tencent": { x: 2662, y: -775 },
      "WALMART": { x: 1637, y: -1208 },
    },
  },
  // 1:1 view. Un-authored entries inherit the full view; these override it.
  square: {
    settings: { scale: 1.000, collidePadding: 28, sizeSpacing: 0.060, repulsion: 90, sectorPull: 0.160, nameThreshold: 10 },
    sectorCenters: {
      "Advertising": { x: -1100, y: 419 },
      "AI": { x: 1662, y: 649 },
      "Audio": { x: -870, y: 859 },
      "Content Platform": { x: 574, y: -568 },
      "Exhibition": { x: 308, y: 295 },
      "Gaming": { x: 987, y: -1114 },
      "Hardware/Physical": { x: 937, y: 38 },
      "HoldingCo": { x: -719, y: -279 },
      "Large Cap": { x: -1192, y: -2209 },
      "Local TV": { x: -75, y: -1446 },
      "MVPD/BB": { x: -142, y: -940 },
      "PSM": { x: -1543, y: -634 },
      "Publishing": { x: -1089, y: 1403 },
      "Social/Creator": { x: -337, y: 1330 },
      "Sports Leagues": { x: 697, y: 527 },
      "Studio": { x: 155, y: -345 },
      "Telecom": { x: -1290, y: -1724 },
    },
    positions: {
      "Access": { x: -922, y: 12 },
      "Alphabet": { x: -1923, y: -950 },
      "Amazon": { x: 584, y: -1880 },
      "Apple": { x: -1794, y: 1179 },
      "ByteDance": { x: -121, y: 1115 },
      "Charter": { x: -216, y: -713 },
      "Comcast": { x: -585, y: -477 },
      "COX": { x: 11, y: -701 },
      "DAZN": { x: -1250, y: 30 },
      "Deezer": { x: -661, y: 65 },
      "Disney": { x: 564, y: -843 },
      "Marvel": { x: 581, y: -505 },
      "META": { x: -485, y: 2072 },
      "MFE": { x: 378, y: 34 },
      "Microsoft": { x: 1059, y: 1335 },
      "Netflix": { x: -20, y: 370 },
      "Nexstar": { x: -833, y: -1108 },
      "Nvidia": { x: 1725, y: -290 },
      "Open AI": { x: 1730, y: 1949 },
      "Oracle": { x: 338, y: 1961 },
      "Paramount Skydance": { x: 342, y: 1391 },
      "ProSieben": { x: 644, y: 43 },
      "Reliance": { x: -1172, y: 1960 },
      "Samsung": { x: -572, y: -1884 },
      "Spotify": { x: -832, y: 857 },
      "TEGNA": { x: -932, y: -1274 },
      "Tik Tok US": { x: 109, y: 1565 },
      "WALMART": { x: 1751, y: -1621 },
      "WBD": { x: 335, y: 1043 },
      "WMG": { x: -942, y: 214 },
      "Xumo": { x: -580, y: -712 },
    },
  },
};
