// Per-view-type mobile layouts — the mobile counterpart to layout.ts, one
// independent layout per mobile view type (full / vertical / horizontal /
// square). Each has its own physics settings, hand-placed planet positions, and
// sector gravity wells, all separate from desktop AND from each other. Authored
// in the browser via `?edit=mobile` (view-type selector + drag + sliders), then
// copied back here. Coordinates are in each type's own canvas slide-space.
//
// Local fallback, same pattern as layout.ts: a future Sanity migration swaps
// these for per-view-type fields on each company.
export type MobilePosition = { x: number; y: number };
export type MobileViewType = "full" | "vertical" | "horizontal" | "square";

export type MobileSettings = {
  scale: number; // planet-size multiplier (1 = auto)
  collidePadding: number; // min gap between planets (no overlap)
  sizeSpacing: number; // extra gap scaled by planet radius
  repulsion: number; // long-range push that fills empty space
  sectorPull: number; // gravity toward each sector's center (lower = fills more)
  nameThreshold: number; // min on-screen planet diameter (px) to show a name
};

export type MobileLayout = {
  settings: MobileSettings;
  positions: Record<string, MobilePosition>; // hand-placed planets (pinned)
  sectorCenters: Record<string, MobilePosition>; // per-sector gravity wells
};

// Generated by ?edit=mobile. Paste over MOBILE_LAYOUTS here.
export const MOBILE_LAYOUTS: Record<MobileViewType, MobileLayout> = {
  full: {
    settings: { scale: 1.000, collidePadding: 12, sizeSpacing: 0.050, repulsion: 16, sectorPull: 0.050, nameThreshold: 6 },
    sectorCenters: {
      "Advertising": { x: -1261, y: 411 },
      "Audio": { x: -773, y: 929 },
      "Content Platform": { x: 999, y: -328 },
      "Exhibition": { x: 198, y: 476 },
      "Gaming": { x: 1498, y: -754 },
      "Hardware/Physical": { x: 953, y: 274 },
      "HoldingCo": { x: -453, y: 54 },
      "Large Cap": { x: -1145, y: -1336 },
      "Local TV": { x: -398, y: -876 },
      "MVPD/BB": { x: 233, y: -573 },
      "PSM": { x: -1971, y: -146 },
      "Publishing": { x: -1070, y: 1523 },
      "Social/Creator": { x: -133, y: 1388 },
      "Sports Leagues": { x: 978, y: 883 },
      "Studio": { x: 430, y: -12 },
      "Telecom": { x: -1925, y: -1010 },
    },
    positions: {
      "Alibaba": { x: 2281, y: -1167 },
      "Alphabet": { x: -1125, y: -380 },
      "Amazon": { x: 665, y: -1143 },
      "Apple": { x: -1969, y: 1199 },
      "ByteDance": { x: -56, y: 1070 },
      "Charter": { x: -12, y: -460 },
      "Comcast": { x: -4, y: -234 },
      "COX": { x: 208, y: -458 },
      "Disney": { x: 25, y: 113 },
      "Marvel": { x: 25, y: 338 },
      "META": { x: -337, y: 2105 },
      "Microsoft": { x: 1433, y: 1842 },
      "Nexstar": { x: -643, y: -962 },
      "Open AI": { x: 2311, y: 2197 },
      "Oracle": { x: 468, y: 1805 },
      "Paramount Skydance": { x: 472, y: 1222 },
      "Reliance": { x: -1172, y: 2012 },
      "Samsung": { x: -306, y: -1423 },
      "Space X": { x: 2506, y: 1437 },
      "TEGNA": { x: -745, y: -1108 },
      "Tik Tok US": { x: 219, y: 1429 },
      "WALMART": { x: 1651, y: -1371 },
      "WBD": { x: 465, y: 952 },
      "Xumo": { x: -220, y: -379 },
    },
  },
  vertical: {
    settings: { scale: 1.000, collidePadding: 12, sizeSpacing: 0.050, repulsion: 26, sectorPull: 0.050, nameThreshold: 6 },
    sectorCenters: {
      "Advertising": { x: 414, y: -302 },
      "Audio": { x: -384, y: 414 },
      "Content Platform": { x: 195, y: -561 },
      "Exhibition": { x: 125, y: 806 },
      "Gaming": { x: 525, y: -912 },
      "Hardware/Physical": { x: 297, y: 3 },
      "HoldingCo": { x: -321, y: -416 },
      "Large Cap": { x: 143, y: 1593 },
      "Local TV": { x: -350, y: -766 },
      "MVPD/BB": { x: 69, y: -934 },
      "PSM": { x: -775, y: -225 },
      "Publishing": { x: -278, y: 75 },
      "Social/Creator": { x: -511, y: 763 },
      "Sports Leagues": { x: 310, y: 435 },
      "Studio": { x: 631, y: -529 },
      "Telecom": { x: -546, y: -1045 },
    },
    positions: {
      "Access": { x: -452, y: -170 },
      "Alibaba": { x: 706, y: -1171 },
      "Alphabet": { x: -851, y: -652 },
      "Amazon": { x: 863, y: -583 },
      "Antrhopic": { x: 506, y: 799 },
      "Apple": { x: -919, y: 248 },
      "ByteDance": { x: -117, y: 307 },
      "Charter": { x: -54, y: -759 },
      "Comcast": { x: -23, y: -537 },
      "COX": { x: 47, y: -805 },
      "DAZN": { x: -334, y: -173 },
      "Deezer": { x: -557, y: -169 },
      "Disney": { x: 139, y: -386 },
      "Epic": { x: 282, y: -612 },
      "Marvel": { x: 136, y: -241 },
      "META": { x: -848, y: 910 },
      "MFE": { x: 431, y: -497 },
      "Microsoft": { x: -118, y: 1177 },
      "Netflix": { x: -80, y: -222 },
      "Nexstar": { x: -271, y: -688 },
      "Nvidia": { x: 808, y: 173 },
      "Open AI": { x: 562, y: 1150 },
      "Oracle": { x: 136, y: 658 },
      "Paramount Skydance": { x: 129, y: 349 },
      "ProSieben": { x: 490, y: -432 },
      "Reliance": { x: -294, y: 695 },
      "Riot": { x: 206, y: -695 },
      "Samsung": { x: -249, y: -1168 },
      "Space X": { x: 914, y: 831 },
      "TEGNA": { x: -263, y: -784 },
      "Tencent": { x: 375, y: -777 },
      "Tik Tok US": { x: 4, y: 474 },
      "WALMART": { x: 281, y: -1169 },
      "WBD": { x: 120, y: 130 },
      "WMG": { x: -451, y: -31 },
      "Xumo": { x: -147, y: -668 },
    },
  },
  // Landscape (rotated-phone) view. Empty entries inherit the full view's
  // placement + wells at runtime; these override it. Portrait → rotate prompt.
  horizontal: {
    settings: { scale: 1.000, collidePadding: 12, sizeSpacing: 0.050, repulsion: 16, sectorPull: 0.050, nameThreshold: 6 },
    sectorCenters: {
      "Audio": { x: -766, y: 894 },
      "Content Platform": { x: 962, y: -335 },
      "Exhibition": { x: 64, y: 462 },
      "Gaming": { x: 1401, y: -699 },
      "Hardware/Physical": { x: 851, y: 107 },
      "Studio": { x: 158, y: -172 },
    },
    positions: {
      "Alibaba": { x: 2281, y: -1167 },
      "Antrhopic": { x: 2799, y: 734 },
      "Epic": { x: 2289, y: -707 },
      "META": { x: -426, y: 1916 },
      "Microsoft": { x: 1247, y: 1292 },
      "Nvidia": { x: 1891, y: 129 },
      "Open AI": { x: 1988, y: 1905 },
      "Reliance": { x: -1207, y: 1920 },
      "Riot": { x: 2409, y: -531 },
      "Samsung": { x: -348, y: -1269 },
      "Space X": { x: 2543, y: 1438 },
      "Tencent": { x: 2662, y: -775 },
      "WALMART": { x: 1637, y: -1208 },
    },
  },
  // 1:1 view. Un-authored entries inherit the full view; these override it.
  square: {
    settings: { scale: 1.000, collidePadding: 28, sizeSpacing: 0.060, repulsion: 90, sectorPull: 0.160, nameThreshold: 6 },
    sectorCenters: {
      "Advertising": { x: -1100, y: 419 },
      "AI": { x: 1141, y: 449 },
      "Audio": { x: -870, y: 859 },
      "Content Platform": { x: 649, y: -372 },
      "Exhibition": { x: 123, y: 280 },
      "Gaming": { x: 772, y: -1174 },
      "Hardware/Physical": { x: 788, y: 89 },
      "HoldingCo": { x: -719, y: -279 },
      "Large Cap": { x: -1192, y: -2209 },
      "Local TV": { x: -75, y: -1446 },
      "MVPD/BB": { x: -142, y: -940 },
      "PSM": { x: -1282, y: -509 },
      "Publishing": { x: -1089, y: 1403 },
      "Social/Creator": { x: -467, y: 1355 },
      "Sports Leagues": { x: 421, y: 592 },
      "Studio": { x: 20, y: -420 },
      "Telecom": { x: -1290, y: -1724 },
    },
    positions: {
      "Access": { x: -922, y: 12 },
      "Alibaba": { x: 878, y: -706 },
      "Alphabet": { x: -1777, y: -853 },
      "Amazon": { x: 584, y: -1880 },
      "Antrhopic": { x: 1659, y: 715 },
      "Apple": { x: -1800, y: 851 },
      "ByteDance": { x: -296, y: 1065 },
      "Charter": { x: -216, y: -713 },
      "Comcast": { x: -585, y: -477 },
      "COX": { x: 11, y: -701 },
      "DAZN": { x: -1250, y: 30 },
      "Deezer": { x: -661, y: 65 },
      "Disney": { x: 399, y: -773 },
      "Epic": { x: 1145, y: -1111 },
      "Marvel": { x: 406, y: -565 },
      "META": { x: -620, y: 2067 },
      "MFE": { x: 233, y: -6 },
      "Microsoft": { x: 909, y: 1245 },
      "Netflix": { x: -301, y: 525 },
      "Nexstar": { x: -833, y: -1108 },
      "Nvidia": { x: 1810, y: -280 },
      "Open AI": { x: 1500, y: 1929 },
      "Oracle": { x: 72, y: 1871 },
      "Paramount Skydance": { x: 182, y: 1436 },
      "ProSieben": { x: 403, y: -7 },
      "Reliance": { x: -1430, y: 1840 },
      "Riot": { x: 1222, y: -906 },
      "Samsung": { x: -572, y: -1884 },
      "Space X": { x: 1880, y: 1391 },
      "Spotify": { x: -832, y: 857 },
      "TEGNA": { x: -932, y: -1274 },
      "Tencent": { x: 1494, y: -1210 },
      "Tik Tok US": { x: -91, y: 1510 },
      "WALMART": { x: 1495, y: -1835 },
      "WBD": { x: 245, y: 1113 },
      "WMG": { x: -942, y: 214 },
      "Xumo": { x: -580, y: -712 },
    },
  },
};
