// Canvas bounding box in slide-coord space — drives the SVG viewBox and the
// physics bounds. Two layouts: a wide landscape canvas for desktop, and a
// portrait canvas for mobile so planets fill a vertical viewport.
// Canvas centered so the SECTOR_CENTERS centroid (~x=303) sits at the canvas
// center. The original `x: -1875` left ~350 slide-units of empty room on the
// right side because most sectors live in the left two-thirds of the layout.
export const CANVAS_DESKTOP = { x: -2225, y: -1253, w: 5052, h: 3279 };
export const CANVAS_MOBILE = { x: -1200, y: -2500, w: 2400, h: 5000 };
// 4:5 portrait canvas for the mobile "vertical" view + its hand-placed layout,
// authored via the ?edit=mobile browser editor.
export const CANVAS_MOBILE_45 = { x: -1000, y: -1250, w: 2000, h: 2500 };
// 16:9 landscape canvas for the mobile "horizontal" (rotated-phone) view.
export const CANVAS_MOBILE_HORIZONTAL = { x: -1280, y: -720, w: 2560, h: 1440 };
// 1:1 canvas for the mobile "square" view. Sized to contain the full view's
// placement (which it inherits) so planets start visible before manual tuning.
export const CANVAS_MOBILE_SQUARE = { x: -2000, y: -2000, w: 4000, h: 4000 };

import type { OmbreStripes } from "@media-map/map-core";

// Sector → canvas position (slide-coord space). These are the "gravity wells"
// the physics simulation pulls each sector's planets toward.
//
// Edit these positions to relocate a sector on the map. Sector names below
// match the values in the SECTOR column of the Google Sheet (case-insensitive
// match — see `lookupSectorCenter`).
// Canvas spans x: -1875 → 3177, y: -1253 → 2026 (center ≈ 688, 386).
// Sector centers are distributed so the visual centroid sits near (688, 386).
// Generated by the in-app design mode. Replace SECTOR_CENTERS in src/sectors.ts with this.
// Generated by the in-app design mode. Replace SECTOR_CENTERS in src/sectors.ts with this.
// Generated by the in-app design mode. Replace SECTOR_CENTERS in src/sectors.ts with this.
// Generated by the in-app design mode. Replace SECTOR_CENTERS in src/sectors.ts with this.
// Generated by the in-app design mode. Replace SECTOR_CENTERS in src/sectors.ts with this.
// Generated by the in-app design mode. Replace SECTOR_CENTERS in src/sectors.ts with this.
// Generated by the in-app design mode. Replace SECTOR_CENTERS in src/sectors.ts with this.
export const SECTOR_CENTERS: Record<string, { x: number; y: number }> = {
  "Telecom": { x: -1571, y: -685 },
  "Local TV": { x: -361, y: -593 },
  "Hardware/Physical": { x: 732, y: 436 },
  "PSM": { x: -1200, y: -150 },
  "Content Platform": { x: 898, y: 215 },
  "Studio": { x: 149, y: -16 },
  "MVPD/BB": { x: -101, y: -317 },
  "HoldingCo": { x: -371, y: 144 },
  "Advertising": { x: -464, y: 433 },
  "Large Cap": { x: 328, y: 402 },
  "Sports Leagues": { x: 1179, y: 679 },
  "Publishing": { x: -1300, y: 900 },
  "Audio": { x: -400, y: 900 },
  "Gaming": { x: 1326, y: -301 },
  "Exhibition": { x: 297, y: 631 },
  "Social/Creator": { x: -400, y: 1450 },
  "AI": { x: 2407, y: 1393 },
  "Uncategorized": { x: 688, y: 386 },
};






// Mobile sector centers — two-column grid arranged top-to-bottom inside
// CANVAS_MOBILE. Large Cap sits solo on its center row since its planets
// (Apple, etc.) are large and need vertical clearance from the side rows.
//
// X positions are pushed near the canvas edges (±900 in a 2400-wide canvas)
// so that with `xMidYMid slice` the side-column planets extend visually to the
// edges of the phone screen. Y range is kept inside [-1900, 1900] so the top
// and bottom rows aren't clipped on common phone aspect ratios.
export const SECTOR_CENTERS_MOBILE: Record<string, { x: number; y: number }> = {
  "Telecom":           { x: -900, y: -1900 },
  "MVPD/BB":           { x:  900, y: -1900 },

  "Local TV":          { x: -900, y: -1525 },
  "Content Platform":  { x:  900, y: -1525 },

  "PSM":               { x: -900, y: -1150 },
  "Studio":            { x:  900, y: -1150 },

  "HoldingCo":         { x: -900, y:  -775 },
  "Advertising":       { x:  900, y:  -775 },

  "Large Cap":         { x:    0, y:     0 },

  "Publishing":        { x: -900, y:   775 },
  "Audio":             { x:  900, y:   775 },

  "Sports Leagues":    { x: -900, y:  1150 },
  "Gaming":            { x:  900, y:  1150 },

  "Exhibition":        { x: -900, y:  1525 },
  "Hardware/Physical": { x:  900, y:  1525 },

  "Social/Creator":    { x: -900, y:  1900 },
  "AI":                { x:  900, y:  1900 },

  "Uncategorized":     { x:    0, y:     0 },
};

// Planet style — drives the look of a single planet. A sector entry sets the
// default look for every planet in that sector; a company entry overrides the
// sector look for one company (e.g. NVIDIA inside Large Cap).
//
// - `fill`        : single flat color. Used when there are no `stripes`.
// - `stripes`     : array of colors. When 2+ are present, the planet renders as
//                   equal-width stripes in the chosen orientation. `fill` is
//                   ignored.
// - `stripeOrientation` : "vertical" (default), "horizontal", or "diagonal" (45°).
// - `stroke`      : optional outline color. Defaults to fill (or first stripe)
//                   at 0.55 alpha.
// - `strokeWidthPx` : optional outline width in screen pixels. Defaults to a
//                     small fraction of the planet radius.
export type StripeOrientation = "horizontal" | "vertical" | "diagonal";
export type PlanetStyle = {
  fill?: string;
  stripes?: string[];
  // Ombré stripe recipe (wins over `stripes`); see map-core's OmbreStripes.
  ombre?: OmbreStripes;
  stripeOrientation?: StripeOrientation;
  stroke?: string;
  strokeWidthPx?: number;
  // Soft glow rendered behind the planet (e.g. PSM = yellow planet on a
  // halo of red). `spreadPx` extends the glow beyond the planet's radius;
  // `blurPx` is the Gaussian blur amount. Both are in screen pixels.
  glow?: {
    color: string;
    blurPx?: number;
    spreadPx?: number;
  };
  // Sidebar-only override. When set, the sector's indicator dot and checkbox
  // render with this CSS `background` value (gradient, etc.). Has no effect
  // on planet rendering — use this when a sector's planets vary too much for
  // any single color to represent them (e.g. Large Cap, where each company
  // gets its own brand palette).
  swatchBackground?: string;
};

// Sector-level default styles. Sectors not listed fall back to the legacy
// HSL gradient look driven by SECTOR_HUES.
export const SECTOR_FLAT_STYLES: Record<string, PlanetStyle> = {
  "Audio":          { fill: "#ff791f" },
  "Advertising":    { fill: "#ef6262" },
  "Local TV":       { fill: "#fbbcfa" },
  "Content Platform": { fill: "#ffffa9" },
  "Telecom":        { fill: "#53a11e" },
  "Gaming":         { fill: "#9437ff" },
  "Sports Leagues": { fill: "#710f20" },
  "AI":             { fill: "#000000", stroke: "#FFFFFF", strokeWidthPx: 0.5 },
  "MVPD/BB":        { fill: "#ffc000" },
  "Publishing":     { fill: "#FFFFFF" },
  "HoldingCo":      { fill: "#9f570f" },
  "Studio":         { fill: "#ef1a1a" },
  "Hardware/Physical": { fill: "#b8b8b8" },
  "PSM":            {
    fill: "#fcfc06",
    glow: { color: "#F40B0A", blurPx: 5, spreadPx: 2.8 },
  },
  "Social/Creator": { fill: "#42dcb7" },
  "Exhibition":     { fill: "#ff3fde" },
  // Large Cap: planets vary per-company (Apple, NVIDIA, Alphabet etc. each
  // have their own brand palette). The sector-level entry contributes a
  // rainbow swatch for the sidebar and a transparent stroke that every Large
  // Cap planet inherits (unless a company entry explicitly overrides it).
  "Large Cap":      {
    stroke: "transparent",
    // Vertical color bands (90deg = horizontal sweep, so bands are vertical).
    // The sidebar applies a small filter:blur() on top to soften the transitions.
    swatchBackground:
      "linear-gradient(90deg, #ff3b30, #ff9500, #ffcc00, #34c759, #5ac8fa, #007aff, #af52de)",
  },
};

// Per-company style overrides. Takes precedence over the sector default.
// CMS-friendly shape: each entry is the same `PlanetStyle` object the sector
// map uses, so the CMS only needs to expose one schema.
export const COMPANY_STYLES: Record<string, PlanetStyle> = {
  "Alphabet": { ombre: { stops: ["#9437ff", "#53a11e", "#ffc000", "#ff791f", "#ef1a1a", "#3657fd"], count: 17, angle: 120, blend: "oklab", reverse: false }, stroke: "#969696", strokeWidthPx: 0.5 },
  "Amazon": { ombre: { stops: ["#9f570f", "#18266e", "#b8b8b8"], count: 12, angle: 120, blend: "oklab", reverse: true } },
  "Nvidia": { ombre: { stops: ["#ededed", "#42dcb7", "#2d2d36", "#a1ff62"], count: 14, angle: 120, blend: "oklab", reverse: true }, stroke: "#969696", strokeWidthPx: 1 },
  "Microsoft": { ombre: { stops: ["#ff791f", "#53a11e", "#3657fd", "#ffc000"], count: 12, angle: 120, blend: "oklab", reverse: true } },
  "Samsung": { ombre: { stops: ["#53a11e", "#8196fe", "#3657fd", "#9437ff", "#ef1a1a", "#ff791f", "#ffc000", "#3657fd", "#2d2d36"], count: 20, angle: 120, blend: "oklab", reverse: true } },
  "META": { ombre: { stops: ["#3657fd", "#b8b8b8"], count: 12, angle: 120, blend: "oklab", reverse: false } },
  "Apple": { ombre: { stops: ["#18266e", "#b8b8b8", "#2d2d36"], count: 15, angle: 120, blend: "oklab", reverse: false } },
  "Walmart": { ombre: { stops: ["#ffc000", "#18266e", "#b8b8b8", "#ef6262", "#2d2d36"], count: 10, angle: 120, blend: "oklab", reverse: false } },
  "ByteDance": { ombre: { stops: ["#42dcb7", "#ef1a1a", "#2d2d36", "#42dcb7", "#ef1a1a", "#2d2d36"], count: 24, angle: 120, blend: "oklab", reverse: false } },
  "Netflix": { ombre: { stops: ["#000000", "#ef1a1a"], count: 10, angle: 120, blend: "oklab", reverse: false }, stroke: "#969696", strokeWidthPx: 1 },
  "Alibaba": { ombre: { stops: ["#b8b8b8", "#2d2d36", "#ff791f"], count: 7, angle: 120, blend: "oklab", reverse: false } },
  "Oracle": { ombre: { stops: ["#b8b8b8", "#710f20", "#710f20", "#b8b8b8"], count: 12, angle: 120, blend: "oklab", reverse: false } },
  "Tencent": { ombre: { stops: ["#b8b8b8", "#53a11e", "#9f570f"], count: 12, angle: 120, blend: "oklab", reverse: true } },
  "Reliance": { ombre: { stops: ["#53a11e", "#ef1a1a", "#18266e"], count: 12, angle: 120, blend: "oklab", reverse: false } },
};

// Stable color per sector (HSL hue). Anything not listed gets a hash-derived hue.
export const SECTOR_HUES: Record<string, number> = {
  "Large Cap":          210,
  "Studio":             280,
  "Content Platform":   195,
  "MVPD/BB":            170,
  "Local TV":           150,
  "PSM":                100,
  "Telecom":            190,
  "Sports Leagues":      30,
  "Gaming":             260,
  "Social/Creator":     320,
  "Publishing":          50,
  "Audio":              130,
  "Advertising":         80,
  "HoldingCo":          340,
  "Exhibition":          10,
  "AI":                 240,
  "Hardware/Physical":  200,
  "Uncategorized":        0,
};

// Build a case-insensitive lookup so "telecom"/"TELECOM"/"Telecom" all match.
const centersByLower = new Map<string, { x: number; y: number }>();
const mobileCentersByLower = new Map<string, { x: number; y: number }>();
const huesByLower = new Map<string, number>();
const flatStylesByLower = new Map<string, PlanetStyle>();
const companyStylesByLower = new Map<string, PlanetStyle>();
const canonicalByLower = new Map<string, string>();
for (const k of Object.keys(SECTOR_CENTERS)) {
  centersByLower.set(k.toLowerCase(), SECTOR_CENTERS[k]);
  canonicalByLower.set(k.toLowerCase(), k);
}
for (const k of Object.keys(SECTOR_CENTERS_MOBILE)) {
  mobileCentersByLower.set(k.toLowerCase(), SECTOR_CENTERS_MOBILE[k]);
}
for (const k of Object.keys(SECTOR_HUES)) {
  huesByLower.set(k.toLowerCase(), SECTOR_HUES[k]);
}
for (const k of Object.keys(SECTOR_FLAT_STYLES)) {
  flatStylesByLower.set(k.toLowerCase(), SECTOR_FLAT_STYLES[k]);
}
for (const k of Object.keys(COMPANY_STYLES)) {
  companyStylesByLower.set(k.toLowerCase(), COMPANY_STYLES[k]);
}

export function normSector(s: string | undefined): string {
  const t = (s ?? "").trim();
  if (!t) return "Uncategorized";
  // If it matches a known sector (case-insensitive), return the canonical form
  // so positions and colors line up.
  return canonicalByLower.get(t.toLowerCase()) ?? t;
}

function hashHue(s: string): number {
  let h = 0;
  for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) >>> 0;
  return h % 360;
}

export function hueForSector(sector: string): number {
  return huesByLower.get(sector.toLowerCase()) ?? hashHue(sector);
}

/**
 * Style for a single planet. The sector default provides baseline fields; the
 * per-company override extends/overrides individual keys. Either may be absent.
 *
 * Example: Large Cap sets `stroke: "transparent"` at the sector level; Apple's
 * company entry adds `stripes` + `stripeOrientation` but inherits the transparent
 * stroke from the sector default.
 */
// Every planet's default outline in the fallback look (matches Sanity, where it
// lives on each sector's default style). Kept out of SECTOR_FLAT_STYLES because
// the sidebar reads a sector's `stroke` as its swatch border / checkbox accent.
const PLANET_OUTLINE: PlanetStyle = { stroke: "#969696", strokeWidthPx: 0.75 };

export function planetStyleFor(name: string, sector: string): PlanetStyle | null {
  const company = companyStylesByLower.get(name.toLowerCase());
  const sec = flatStylesByLower.get(sector.toLowerCase());
  if (!company && !sec) return null;
  return { ...(sec ?? {}), ...PLANET_OUTLINE, ...(company ?? {}) };
}

/** Sidebar swatches show the sector default, never a per-company override. */
export function flatStyleForSector(sector: string): PlanetStyle | null {
  return flatStylesByLower.get(sector.toLowerCase()) ?? null;
}

/** Convert "#EE7D31" (or "#eee") to "rgba(r, g, b, a)". */
export function hexToRgba(hex: string, alpha: number): string {
  let h = hex.replace("#", "");
  if (h.length === 3) h = h.split("").map(c => c + c).join("");
  const r = parseInt(h.substring(0, 2), 16);
  const g = parseInt(h.substring(2, 4), 16);
  const b = parseInt(h.substring(4, 6), 16);
  return `rgba(${r}, ${g}, ${b}, ${alpha})`;
}

export function isKnownSector(sector: string): boolean {
  return centersByLower.has(sector.toLowerCase());
}

/**
 * Resolve a sector center. Unknown sectors get auto-placed on a ring around
 * the canvas center, ordered by `index` so positions stay stable across renders.
 */
export function sectorCenterFor(
  sector: string,
  index: number,
  totalUnknown: number,
  mobile = false,
): { x: number; y: number } {
  const centers = mobile ? mobileCentersByLower : centersByLower;
  const known = centers.get(sector.toLowerCase());
  if (known) return known;
  const angle = (index / Math.max(1, totalUnknown)) * Math.PI * 2;
  if (mobile) {
    const radius = 900;
    return { x: Math.cos(angle) * radius, y: Math.sin(angle) * radius };
  }
  const radius = 1400;
  return {
    x: 688 + Math.cos(angle) * radius,
    y: 386 + Math.sin(angle) * radius,
  };
}
